import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import { Card } from "react-bootstrap";

// @ts-ignore
const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const stocks = ["AMD", "IBM", "AAPL"];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {stocks.map((symbol) => (
          <SymbolInfo key={symbol} symbol={symbol} />
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export function SymbolInfo({ symbol }: { symbol: string }) {
  const { data, error } = useSWR(`/api/get-quotes?symbol=${symbol}`, fetcher);
  const result = data?.quoteResponse?.result[0];

  return (
    <Card>
      <Card.Header>
        <h5>{symbol}</h5>
        <h6>
          {result?.shortName} ${result?.regularMarketPrice}
        </h6>
      </Card.Header>
      <Card.Body>
        <details>
          <summary>JSON</summary>
          <pre>{JSON.stringify(result, null, 2)}</pre>
        </details>
      </Card.Body>
    </Card>
  );
}
