import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import { Card } from "react-bootstrap";
import React from "react";
import {
  CategoryScale,
  Chart as ChartJS,
  Legend,
  LinearScale,
  LineElement,
  PointElement,
  Title,
  Tooltip,
} from "chart.js";
import { Line } from "react-chartjs-2";

// @ts-ignore
const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const stocks = ["AMD", "IBM", "AAPL"];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {stocks.map((symbol) => (
          <SymbolInfo key={symbol} symbol={symbol} />
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export function SymbolInfo({ symbol }: { symbol: string }) {
  const { data, error } = useSWR(`/api/get-quotes?symbol=${symbol}`, fetcher);
  const result = data?.quoteResponse?.result[0];

  return (
    <Card>
      <Card.Header>
        <h5>{symbol}</h5>
        <h6>
          {result?.shortName} ${result?.regularMarketPrice}
        </h6>
      </Card.Header>
      <Card.Body>
        <SymbolChart symbol={symbol} />
        <details>
          <summary>JSON</summary>
          <pre>{JSON.stringify(result, null, 2)}</pre>
        </details>
      </Card.Body>
    </Card>
  );
}

export function SymbolChart({ symbol }: { symbol: string }) {
  const { data, error } = useSWR(`/api/get-chart?symbol=${symbol}`, fetcher);
  const result = data?.chart?.result?.[0];

  return (
    <>
      {result && <LineChart data={result} />}
      <details>
        <summary>JSON</summary>
        <pre>{JSON.stringify(result, null, 2)}</pre>
      </details>
    </>
  );
}

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

export function LineChart({ data }: any) {
  const options = {
    responsive: true,
    plugins: {
      legend: {
        position: "top" as const,
      },
      title: {
        display: true,
        text: "Chart.js Line Chart",
      },
    },
    scales: {
      xAxis: {
        // The axis for this scale is determined from the first letter of the id as `'x'`
        // It is recommended to specify `position` and / or `axis` explicitly.
        ticks: {
          // Include a dollar sign in the ticks
          // callback: (value, index, ticks) => "$" + value,
        },
      },
    },
  };

  const labels = data.timestamp.map((x) =>
    new Date(x * 1000).toISOString().substring(0, 10)
  );

  const lineChart = {
    labels,
    datasets: [
      {
        label: "6 months by 1 day",
        data: data.indicators.quote[0].close,
        borderColor: "rgb(255, 99, 132)",
        backgroundColor: "rgba(255, 99, 132, 0.5)",
      },
      // {
      //   label: 'Dataset 2',
      //   data: labels.map(() => faker.datatype.number({ min: -1000, max: 1000 })),
      //   borderColor: 'rgb(53, 162, 235)',
      //   backgroundColor: 'rgba(53, 162, 235, 0.5)',
      // },
    ],
  };

  return <Line options={options} data={lineChart} height={200} />;
}
